### ISSUE TITLE
Memory management (of SDL resources)

### ISSUE THREAD

**Issue by Memorix101** [Aloshi/dukglue#4]
Hey,

I want to ask about memory management. I use duktape/dukglue together with SDL and want to know
what I can do to free my SDL context after destroying the duktape heap. I want to do that automatically.

My SDL context is binded to duktape context. I call it like:

#### C++
`````C++
dukglue_register_constructor<graphics>(ctx, "Texture");
dukglue_register_method(ctx, &graphics::load, "load");
`````

#### JavaScript
`````javascript
var texture = new Texture();
texture.load("nyancat.png");
`````

Currently, it's not being freed after calling `duk_destroy_heap(ctx);`

**Comment by KaCMaHaBT** [comment]
You can register deleter and free object manually. This is a reason why we dropped to use dukglue.

**Comment by Memorix101** [comment]
@KaCMaHaBT Yep, I'm currently using them. Would you like to tell me what you use :)

**Comment by KaCMaHaBT** [comment]
We made objects on raw duktape, and made some things on dukglue, using it as a objectfactory. I didn't found a way to put a dukglue object under garbage collector.

**Comment by Aloshi** [comment]
This is probably not the answer you are hoping for, but there's currently no way to do automatic memory management like this with Dukglue. Check README.md for an explanation. There are 2 major roadblocks:

1. Dukglue needs to keep a map of pointer -> Duktape object to make sure that every time you return a particular pointer from a script, it returns the same Duktape object (so that equality checks work as you'd expect and scripted properties are preserved). Unfortunately, this mapping prevents objects from ever being garbage collected (Duktape does not support weak object references). This is only a problem if you are returning objects from registered C++ functions/methods.
2. The tricky bit is moving ownership between script and C++ code. Here's a slightly contrived example:

JavaScript:
```js
function setUpPlayer() {
  Player p = new Player();
  p.setPosition(5, 12);
  return p;
}
```

C++:
```cpp
Player* p = dukglue_peval<Player*>(ctx, "setUpPlayer()");
// if we use the Duktape GC to manage our memory,
// p was just deleted because its refcount hit zero when it was popped from the stack!
```

---

That said, I think support may be possible to add, but with a few rather harsh restrictions:

1. The object must be created in script (as in your example).
2. You promise to avoid a situation like the example above. If the object is passed into C++ code as an argument, your C++ code must either not keep a reference to the object or be able to handle it suddenly being destroyed (e.g. through some sort of global cleanup triggered by the object's destructor). I can't really add any safeguards here.
3. You promise to never push objects created in script from C++ (i.e. never return it from a registered C++ function/method). You can use it as an argument to a native function/method, but not return it (because this will cause Dukglue to set up a reference to it in the heap stash, which will prevent it from ever being garbage collected).

I would add this as an additional option when registering a constructor, e.g. `dukglue_register_constructor_managed(...)`. This would set up the object with a special prototype with a custom finalizer that would automatically delete the C++ object when it is GC'd. It would be up to the user to make sure they don't break any of the promises above, though. Do you think this would work for you?

(Restriction 2 could possibly be lifted if I did something fancy with `std::shared_ptr`, but I don't think it's worth the time (to me personally) right now.)

Long post, but the solution I outlined is not that hard to implement. Length is mostly due to me trying to think this through. 😄

**Comment by Memorix101** [comment]
I think this should work. Thanks for your answer :)

**Comment by Memorix101** [comment]
btw I've another question maybe you can help.

In my javascript I made arrays with my SDL object, but when I pop them my the script eval process is stopped at the array.pop statement. 

I give you an example:

C++
````C++
graphics::graphics()
{
	SDL_Surface* sur = NULL;
	SDL_Texture* tex = NULL;
	SDL_RWops* SUR_RW = NULL;
}

dukglue_register_constructor<graphics>(ctx, "gfx");
dukglue_register_method(ctx, &graphics::load, "load");
dukglue_register_method(ctx, &graphics::draw, "draw");
````

JavaScript
````javascript
            bulletList.push({
                tex: new gfx(),
                pos: new vector2(player.pos.x + 9, player.pos.y - 13),
                hitbox: new rect(0, 0, 6, 36),
                alive: true
            });

        bulletList.forEach(function(element) {
            if (element.pos.y < 0) {
                element.alive = false;
                element.tex.free();
                element.pop(); // or splice what ever frees it from the stack here
            }

        });

````

This example is a laser bullet, but when I try to removed it because it hit an enemy or is out of screen all code related to is not executed after the pop statement (i guess because something fails here)

you can read the full code [here](https://github.com/G-eon/g-eon-space-invaders/blob/master/main.js)

btw the line `element.tex.free();`

is called in C++ like

````c++
void graphics::free()
{
	remove = true; // if true blitting in draw method will be skipped

	SDL_DestroyTexture(tex);
	tex = NULL; // to be safe

	SDL_FreeRW(SUR_RW);
	SUR_RW = NULL; // to be safe

	SDL_FreeSurface(sur);
	sur = NULL; // to be safe
}
````

**Comment by KaCMaHaBT** [comment]
I don't know is my fork available for look?

Some time ago I made two improvements for dukglue.
First one is posibility to put dukglue C++ object to duk stack without 'new' operator.
Second one is little trick with types. The magic C++ function which returns 'const void' is possible to return any object in JS. So these two changes make possible to create global object factory with external C++ garbage collector or deleter.

**Comment by Memorix101** [comment]
@KaCMaHaBT yes it is :)

https://github.com/KaCMaHaBT/dukglue

**Comment by Aloshi** [comment]
Added in commit 2baf340fac60d3f3e962828482f4710cedd8ce4e. Commit message outlines the restrictions. Let me know if there are any problems with it.
